FROM nginx:stable-alpine

RUN apk add --no-cache certbot certbot-nginx bash

# Copy prebuilt frontend
COPY ./frontend/dist /var/www/html

# Copy nginx config
COPY ./deploy/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
