# docker-compose.yml

version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    environment:
      DB_URI : "mongodb://mongo_container:27017/myDatabase"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app   #Bind mount
      - /app/node_modules

  mongo:
    image: mongo:latest
    container_name : 'mongo_container'
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    
volumes:
  mongo-data: