version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./frontend/.env
    # Nginx + Certbot mounts
    volumes:
      # Use /etc/nginx/conf.d for Alpine or /etc/nginx/sites-available for Ubuntu
      - ./deploy/default.conf:/etc/nginx/conf.d/default.conf
      # Mount host cert storage (persist across rebuilds)
      - /var/certs/etc-letsencrypt:/etc/letsencrypt
    depends_on:
      - backend

volumes:
  mongodata:
