version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    ports:
      - "3000:3000"

  frontend:
    image: frontend:latest   # Use a prebuilt image
    container_name: frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./frontend/.env
    volumes:
      - ./deploy/default.conf:/etc/nginx/conf.d/default.conf
      - /var/certs/etc-letsencrypt:/etc/letsencrypt
    depends_on:
      - backend

volumes:
  mongodata:
              
